# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=100)),
            ],
        ),
    ]
